config/routes.rb
ComicBooks::Application.routes.draw do
  get "value/add"

  get "value/list"

  resources :comics do
    member do
      get 'viewed'
    end
  end

end

app/models/comic.rb
class Comic < ActiveRecord::Base
  attr_accessible :issue, :publisher, :synopsis, :title, :year

  has_many :view_histories

end

app/models/value.rb
class Value < ActiveRecord::Base
  attr_accessible :sixty_price, :ninetyfour_price, :thirteen_price, :notes
end

app/models/view_history.rb
class ViewHistory < ActiveRecord::Base
  attr_accessible :comic_id, :ip, :time_viewed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  # GET /comics
  # GET /comics.json

  def viewed
    comic = Comic.find(params[:id])
    @views = comic.view_histories
  end

  def index
    @comics = Comic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comic = Comic.find(params[:id])

    vh = ViewHistory.new(:time_viewed => Time.now, :ip => request.remote_ip,
    :comic_id => @comic.id)
    vh.save


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/new
  # GET /comics/new.json
  def new
    @comic = Comic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/1/edit
  def edit
    @comic = Comic.find(params[:id])
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(params[:comic])

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render json: @comic, status: :created, location: @comic }
      else
        format.html { render action: "new" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comics/1
  # PUT /comics/1.json
  def update
    @comic = Comic.find(params[:id])

    respond_to do |format|
      if @comic.update_attributes(params[:comic])
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy

    respond_to do |format|
      format.html { redirect_to comics_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/value_controller.rb
class ValueController < ApplicationController
  def add
  end

  def list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/value_helper.rb
module ValueHelper
end

app/views/comics/_form.html.erb
<%= form_for(@comic) do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :issue %><br />
    <%= f.number_field :issue %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br />
    <%= f.text_area :synopsis %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<h1>Listing comics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Issue</th>
    <th>Publisher</th>
    <th>Year</th>
    <th>Synopsis</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.title %></td>
    <td><%= comic.issue %></td>
    <td><%= comic.publisher %></td>
    <td><%= comic.year %></td>
    <td><%= comic.synopsis %></td>
    <td><%= link_to 'Show', comic %></td>
    <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
    <td><%= link_to 'Destroy', comic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comic', new_comic_path %>

app/views/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @comic.title %>
</p>

<p>
  <b>Issue:</b>
  <%= @comic.issue %>
</p>

<p>
  <b>Publisher:</b>
  <%= @comic.publisher %>
</p>

<p>
  <b>Year:</b>
  <%= @comic.year %>
</p>

<p>
  <b>Synopsis:</b>
  <%= @comic.synopsis %>
</p>


<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>

app/views/comics/viewed.html.erb
<h1>Listing comics</h1>

<table>
  <tr>
    <th>Date</th>
    <th>IP</th>
  </tr>

<% @views.each do |view| %>
  <tr>
    <td><%= view.time_viewed %></td>
    <td><%= view.ip %></td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComicBooks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/value/add.html.erb
<h1>Value#add</h1>
<p>Find me in app/views/value/add.html.erb</p>

app/views/value/list.html.erb
<h1>Value#list</h1>
<p>Find me in app/views/value/list.html.erb</p>